llm:
  type: openai
  models:
    openrouter: Null
    openai: "gpt-5"
    anthropic: Null
  api_keys:
    openrouter: ""
    openai: "sk-GTbTKP5X8ZaZHL8kcUWtLBaiJkVow6hsnbhb8qb1ZtYR5pTqkDuu"
    anthropic: ""
  temperature: 0.7

benchmark:
  checkpoint: "checkpoints"
  verbose: true
  output_pattern: "results/{dataset_name}_{model}.json"

